name: FOFA Fetch IP

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次，可根据需要修改
  workflow_dispatch: # 支持手动触发

jobs:
  fetch_ip:
    runs-on: ubuntu-latest
    env:
      FOFA_EMAIL: ${{ secrets.FOFA_EMAIL }}
      FOFA_KEY: ${{ secrets.FOFA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run FOFA fetch script
        run: |
          python fofa_fetch.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.txt
          git commit -m "Update FOFA IP files" || echo "No changes to commit"
          git push
