name: FOFA IP

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install requests

      - name: Run fofa_fetch.py
        run: python fofa_fetch.py